import pytest
from src.models.recipe_image import RecipeImage


def test_create_recipe_image_all_fields():
    image = RecipeImage(
        uuid="abc-123",
        recipe_id=1,
        filename="photo.jpg",
        content_type="image/jpeg",
        size_bytes=12345,
        storage_backend="database",
        storage_ref="abc-123",
        data=b"fake-image-data",
        is_primary=True,
    )
    assert image.uuid == "abc-123"
    assert image.recipe_id == 1
    assert image.filename == "photo.jpg"
    assert image.content_type == "image/jpeg"
    assert image.size_bytes == 12345
    assert image.storage_backend == "database"
    assert image.storage_ref == "abc-123"
    assert image.data == b"fake-image-data"
    assert image.is_primary is True


def test_create_recipe_image_defaults():
    image = RecipeImage(
        uuid="def-456",
        filename="step.png",
        content_type="image/png",
        size_bytes=999,
        storage_backend="filesystem",
    )
    assert image.recipe_id is None
    assert image.storage_ref is None
    assert image.data is None
    assert image.is_primary is False


def test_create_recipe_image_uuid_autogenerated():
    image = RecipeImage(
        filename="test.webp",
        content_type="image/webp",
        size_bytes=500,
        storage_backend="database",
    )
    assert image.uuid is not None
    assert len(image.uuid) > 0


def test_recipe_image_has_timestamps():
    image = RecipeImage(
        uuid="ts-test",
        filename="ts.jpg",
        content_type="image/jpeg",
        size_bytes=100,
        storage_backend="database",
    )
    assert image.created_at is not None
    assert image.updated_at is not None
