"""add_missing_recipe_columns

Revision ID: 18a45e8a1d36
Revises: 0673160ee889
Create Date: 2025-08-09 00:10:41.595763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '18a45e8a1d36'
down_revision: Union[str, None] = '0673160ee889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('difficulty_level', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('recipes', 'instructions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'instructions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('recipes', 'image_url')
    op.drop_column('recipes', 'is_public')
    op.drop_column('recipes', 'difficulty_level')
    # ### end Alembic commands ###
