"""add_recipe_counter_to_tags

Revision ID: 6feb2cd74b06
Revises: 7c9eda6571ed
Create Date: 2025-08-16 18:58:39.287406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6feb2cd74b06'
down_revision: Union[str, None] = '7c9eda6571ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('recipe_counter', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'recipe_counter')
    # ### end Alembic commands ###
