"""make_category_non_nullable

Revision ID: b0b11946c06a
Revises: c4aa69e3d4d9
Create Date: 2025-08-19 00:25:30.726173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0b11946c06a'
down_revision: Union[str, None] = 'c4aa69e3d4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'category',
               existing_type=postgresql.ENUM('Meal Types', 'Special Dietary', 'Course Types', 'Cuisine Types', 'Main Ingredients', 'Cooking Methods', 'Special Categories', name='tagcategory'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'category',
               existing_type=postgresql.ENUM('Meal Types', 'Special Dietary', 'Course Types', 'Cuisine Types', 'Main Ingredients', 'Cooking Methods', 'Special Categories', name='tagcategory'),
               nullable=True)
    # ### end Alembic commands ###
