"""add_category_to_tags

Revision ID: c4aa69e3d4d9
Revises: 6feb2cd74b06
Create Date: 2025-08-18 19:33:07.035193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4aa69e3d4d9'
down_revision: Union[str, None] = '6feb2cd74b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    tagcategory_enum = sa.Enum('Meal Types', 'Special Dietary', 'Course Types', 'Cuisine Types', 'Main Ingredients', 'Cooking Methods', 'Special Categories', name='tagcategory')
    tagcategory_enum.create(op.get_bind())
    
    # Add the column using the created enum type
    op.add_column('tags', sa.Column('category', tagcategory_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'category')
    
    # Drop the enum type
    tagcategory_enum = sa.Enum('Meal Types', 'Dietary', 'Course Types', 'Cuisines', 'Ingredients', 'Cooking', 'Categories', name='tagcategory')
    tagcategory_enum.drop(op.get_bind())
    # ### end Alembic commands ###
